### ISSUE TITLE
Feature extraction parameters should be saved in modelforge models.

### ISSUE THREAD

**Issue by m09** [src-d/style-analyzer#145]
At this point, the modelforge model contains, in addition to the rules themselves, the parameters used during the training of the rules. This doesn't include the parameters used during feature extraction, which are the only one needed to properly apply the rules to new data.

**Comment by m09** [comment]
The saved parameters should also be used instead of the config ones in the `analyze` method of `analyzer.py`.

**Comment by zurk** [comment]
I think it is also useful to add config info for unavoidable future model analysis.

**Comment by m09** [comment]
yes, just saving the complete config seems reasonable to me.

**Comment by vmarkovtsev** [comment]
@zurk Please post the PR here.

**Comment by m09** [comment]
Fixed by #152.
