### ISSUE TITLE
Add more properties for protected attributes of classes

### ISSUE THREAD

**Issue by zurk** [src-d/style-analyzer#161]
See related discussion: 
https://github.com/src-d/style-analyzer/pull/152#discussion_r220461975

@m09, can you please assign me, add the enhancement label and put to Machine Learning project?

**Comment by m09** [comment]
I don't think so actually, almost all our constructor arguments are read-only and only a very small fraction of them are properties right now. I don't like to over-use properties anyway so I'm fine with closing but we have an inconsistent policy atm.

**Comment by vmarkovtsev** [comment]
So reopened.

**Comment by vmarkovtsev** [comment]
Closing as outdated - the upcoming refactoring will cover this anyway.
