### ISSUE TITLE
Setup style-analyzer deployment

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/style-analyzer#162]
- [x] Laptop
- [ ] local-gpu cluster

**Comment by zurk** [comment]
Can not check the first point 🤔. Everything works great. 
local-gpu cluster on the way.

**Comment by zurk** [comment]
We already have a lookout on staging: 
```
➜  style-analyzer git:(feature/features-config) kubectl get pods | grep style
lookout-style-analyzer-4161196046-v8n5x                1/1       Running       0          26d
```
But we do not have a proper release process for style-analyzer. Right now we just update `latest` tag on docker hub: https://hub.docker.com/r/srcd/style-analyzer/tags/.

My next steps:
- [ ] Ensure that style-analyzer on staging works. 
- [ ] Review how everything works for https://github.com/src-d/lookout and https://github.com/src-d/lookout-sonarcheck-analyzer/
- [ ] Setup a proper release process (Apps team uses https://github.com/src-d/ci/tree/v1 maybe we should too).
- [ ] Ask infra to take care of helm chart and CD setup.

@vmarkovtsev we should discuss details. For example, do we want to deploy for each commit to master or for tags only. I think second option is better.

**Comment by zurk** [comment]
I was busy with different demo-related stuff. Now back to this issue.

**Comment by vmarkovtsev** [comment]
@zurk Do we have a helm chart as mentioned in the previous comment?

**Comment by zurk** [comment]
no, we do not. As I understand I should ask an infra for it after everything is running in GKE.
I can create an issue now if you want.

**Comment by zurk** [comment]
@vmarkovtsev I think we can close it as outdated.

**Comment by vmarkovtsev** [comment]
Thanks. This was done in https://github.com/src-d/style-analyzer/pull/327
