### ISSUE TITLE
installing requirements.txt fails with Python 3.7

### ISSUE THREAD

**Issue by smola** [src-d/style-analyzer#175]
See https://github.com/snowballstem/pystemmer/issues/18

It seems adding `cython` explicitly to requirements.txt could solve the issue.

cc @zurk

**Comment by zurk** [comment]
so, the PR into sourced-ml (https://github.com/src-d/ml/pull/319) should fix installation like
```
pip3 install -r requirements.txt
pip3 install .
```

but the problem is deeper and it is not solving regular installation `pip3 install .` See all details in a related issue: https://github.com/src-d/ml/issues/318

**Comment by vmarkovtsev** [comment]
Does it work now @zurk ?

**Comment by zurk** [comment]
Yes. You can not just run `pip3 install .`. It fails if you do not have `Cython` installed.
The current workaround is to run 
```
pip3 install -r requirements.txt
pip3 install .
```
or just 
```
pip3 install Cython
pip3 install .
```

**Comment by vmarkovtsev** [comment]
This is solved by `install_requires` in src-d/ml.

**Comment by vmarkovtsev** [comment]
This is solved by `setup_requires`

**Comment by vmarkovtsev** [comment]
Closing this since the original issue is fixed.
