### ISSUE TITLE
Test that viz tools launch correctly

### ISSUE THREAD

**Issue by m09** [src-d/style-analyzer#197]
Integration tests are needed to make sure that the visualization tools can actually launch since many times recently we had PRs making them out of sync without the CI noticing.

**Comment by m09** [comment]
(Should be done after the demo)

**Comment by EgorBu** [comment]
PR related to this issue: https://github.com/src-d/style-analyzer/pull/217

**Comment by EgorBu** [comment]
PR was merged - do you have any other ideas what else should be checked before closing this issue? @m09

**Comment by m09** [comment]
No it seems perfect, thanks @EgorBu for the PR :+1:
