### ISSUE TITLE
Rule pretty printing bug: {BODY ≥ 1}

### ISSUE THREAD

**Issue by zurk** [src-d/style-analyzer#221]
I see one rule like this:
```
        parents.0.roles = {BODY ≥ 1}
        ∧ left.0.internal_type not in {NullableTypeAnnotation}
        ∧ left.2.diff_offset ≥ 1
        ∧ node.0.start_col ≥ 2
        → y = ␣ (0.96 confidence, 13 support)
```
We should check if Roles rules are printed correctly.

**Comment by m09** [comment]
Why do you think it's a bug? Roles are a set of ordinals, it seems correct to me

**Comment by zurk** [comment]
oh, it is true. but one Node cannot contain two same Roles. So it is better to have it in the same format:
 `parents.0.roles in {BODY}`

**Comment by m09** [comment]
Ok I misunderstood some discussions we had when we coded Roles then, I thought it happened in some cases. Then indeed we have to switch to normal OHE display. I'll PR.

**Comment by m09** [comment]
Close via #237.
