### ISSUE TITLE
Improve the visualizer

### ISSUE THREAD

**Issue by m09** [src-d/style-analyzer#229]
The web-based visualizer we currently have could be improved in many ways on the web-design front. Any improvement is welcome for Hacktoberfest. To list a few:

- add timeout to queries to the server
- improve CSS, layout
- provide a better way to input code (by file upload or giving the path to the server and displaying a file navigator on the client, etc)
- …

**Comment by vmarkovtsev** [comment]
This is how it looks like currently: ![img](https://user-images.githubusercontent.com/2793551/46748584-29aa3400-ccb4-11e8-8c60-4c136aa6d43b.png)

**Comment by vmarkovtsev** [comment]
Manual how to run: https://github.com/src-d/style-analyzer/tree/master/lookout/style/format/visualizer

**Comment by vmarkovtsev** [comment]
@m09 Would be great if you attach here a sample `model.asdf` so that everybody can easily test.

**Comment by m09** [comment]
Has been updated many times since this issue and hacktoberfest is over, I close.
