### ISSUE TITLE
Use signed numbers instead of left.# and right.# in the Visualizer

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/style-analyzer#282]
I suggest to print the rule parts as

```
-1.internal_type
+2.offset
```

instead of

```
left.0.internal_type
right.1.offset
```

I think it will make the rules clearer: the property names will be aligned at 3 chars, also no need to parse "left" and "right".

"parents" are not touched by this.

**Comment by m09** [comment]
btw I can also use `←` and `→` instead of `-` and `+` to indicate left and right (and even `↑` to indicate parents). What do you prefer @src-d/machine-learning?

**Comment by vmarkovtsev** [comment]
I like minus and plus more because they are easier to see for a short-sighted human like me.

For the same reason ∧ seems better than ↑. Besides, using < and > by analogy is still not good because they are harder to distinguish from each other.

**Comment by vmarkovtsev** [comment]
On it today.
