### ISSUE TITLE
Add evaluation for smoke dataset

### ISSUE THREAD

**Issue by zurk** [src-d/style-analyzer#283]
Ancestor: https://github.com/src-d/style-analyzer/issues/207

Related PR: https://github.com/src-d/style-analyzer/pull/276

To continue with this issue I should solve issue https://github.com/src-d/style-analyzer/issues/280 first.

**Comment by zurk** [comment]
Status update:
1. #280 is ready to be merged and I continue with this issue.

After the first analysis it is clear to do the following:

1.  [ ] Add more data to smoke dataset.
2.  [ ] Try to change evaluation measure: use simple edit_distance measure without SequenceMatcher 
3.  [ ] Add threshold for Rule support and confidence to evaluation part
4.  [ ] Add precision and recall metrics

**Comment by zurk** [comment]
PR: https://github.com/src-d/style-analyzer/pull/319


What should be done next:
1. Add tests. As soon as I have more time. 
2. Add Rule support and confidence levels.
3. Create a performance report for the team.

**Comment by zurk** [comment]
Update: 
The code is written, tests are added, minor fixes applied: https://github.com/src-d/style-analyzer/pull/359

Plans:

> 2. Add Rule support and confidence levels.

Best way to do so is to reuse the code directly from `FormatAnalyzer.analyze()` so any further updates will not require more work. It requires additional `FormatAnalyzer` modifications and should be discussed with @vmarkovtsev. 

2. Add precision and recall metrics to report.
3. Create a performance report for the team.

After release:
1.  Add more data and styles to smoke dataset.

**Comment by vmarkovtsev** [comment]
Done
