### ISSUE TITLE
Prepare project to work with source{d} Makefile.main from CI repository

### ISSUE THREAD

**Issue by rporres** [src-d/style-analyzer#291]
@meyskens and myself have been working to add CD to this repository but there are some missing pieces to move on.

https://github.com/src-d/style-analyzer/tree/add-cd-attempt-2 branch contains the last attempt that adds:

* An include on [Makefile.main](https://github.com/src-d/ci/blob/v1/Makefile.main) from CI repository to have deploy and docker targets
* A new job in the stage command to push docker
* A new stage to deploy to staging that has been tested in other repositories (see https://github.com/src-d/lookout-sonarcheck-analyzer or https://github.com/src-d/lookout-gometalint-analyzer)

Makefile.main from CI contains all the needed commands to deploy to a k8s cluster, so it makes sense to use it in this context.

I've pushed a [test tag](https://github.com/src-d/style-analyzer/releases/tag/v0-deploy-test) that's triggered a [failed travis build](https://travis-ci.org/src-d/style-analyzer/builds/448586484) as deploy stage was failing due to:

* Missing PyPi credentials
* Build is failing and so is docker-push

At this point I guess it makes no sense to try to create a PR to add PR as there are missing bits here that beyond the scope of adding CD to a project, hence this issue.

You may find the work on https://github.com/src-d/style-analyzer/tree/add-cd-attempt-2 a starting point for this work.

**Comment by zurk** [comment]
Thank you, guys! I am going to fix the docker image. Somehow bblfsh python package installation is failed.

**Comment by rporres** [comment]
I removed the `docker-build` target in that branch as it was not tagging the image using the travis tag.

**Comment by vmarkovtsev** [comment]
@rporres This is done, correct?

**Comment by rporres** [comment]
Yes. I forgot to close it. Sorry for that.
