### ISSUE TITLE
Publish a docker image \w analyzer

### ISSUE THREAD

**Issue by bzz** [src-d/style-analyzer#30]
As [we have discussed](https://github.com/src-d/minutes/pull/303/files#diff-4ecef06bb119c76851db7bd0fd9d8170R81), In order to start using this analyzer on staging deployment of the lookout, we need to have it's docker image and the best way to share it is to published it on srcd DockerHub.

A simple way to do it is using https://github.com/src-d/ci/tree/v1#docker-build-and-push though a regular release process, as part of CI on git tag.

**Comment by vmarkovtsev** [comment]
So the docker image is pushed after each PR merge since July. Here is the magic command which you need:

```
docker run -it --rm srcd/style-analyzer run lookout.style.format -s 0.0.0.0:2000 --db "postgresql://postgres:postgres@postgres:5432/postgres" --fs /tmp
```

`lookout.style.format` chooses the format analyzer which is currently dummy and will change in the future (in a few weeks).

`0.0.0.0:2000` is the grpc service listen address. By default, the data service is supposed to be the same IP but port `10301`. Override this with `--request-server whatever:10301`.

`--db` requires a running PostgreSQL instance, user `postgres`, password `postgres`, running on host `postgres`, database name `postgres`.

`--fs` points to the directory (volume or local) where to store the models. The dummy implementation writes dummy models so we are safe with `/tmp` for now.

**Comment by vmarkovtsev** [comment]
As of today we are bound to the schema at [5da09179136f01a51f73bd5cbc2b576af6f48aad](https://github.com/src-d/lookout/commit/5da09179136f01a51f73bd5cbc2b576af6f48aad)

**Comment by bzz** [comment]
So cool! 🤝  

Let me try it out and close the issue

**Comment by bzz** [comment]
Steps I have tried:

```
# from https://github.com/src-d/lookout/#without-docker
wget https://raw.githubusercontent.com/src-d/lookout/master/docker-compose.yml
docker-compose up bblfsh postgres

# from https://github.com/src-d/style-analyzer#quick-start
python3 -m lookout init --db "postgresql://postgres:postgres@localhost:5432/postgres" --fs /tmp

docker run -it -p2000:2000 --rm \
    --net lookout_default --link lookout_postgres_1 \
    srcd/style-analyzer run lookout.style.format \
    -s 0.0.0.0:2000 --db "postgresql://postgres:postgres@lookout_postgres_1:5432/postgres" --fs /tmp

/lookout review -v ipv4://localhost:2000 --from c99dcdff172f1cb5505603a45d054998cb4dd606 --to 3a9d78bdd1139c929903885ecb8f811931b8aa70
```

That resulted in analyzer log

```
ERROR:39b9:EventListener:FAIL ?
Traceback (most recent call last):
  File "/lookout/core/event_listener.py", line 161, in wrapped_catch_them_all
    return func(self, request, context)
  File "/lookout/core/event_listener.py", line 182, in wrapped_handle
    return getattr(self.handlers, method_name)(request)
  File "/lookout/core/manager.py", line 66, in wrapped_with_data_request_stub
    return func(self, request)
  File "/lookout/core/manager.py", line 83, in process_review_event
    self._model_id(analyzer), analyzer.model_type, base_url)
  File "/lookout/core/sqla_model_repository.py", line 80, in get
    model = model_type().load(models[0].path)
  File "/usr/local/lib/python3.6/dist-packages/modelforge/model.py", line 67, in load
    cache_dir = os.path.join(self.cache_dir(), self.NAME)
  File "/usr/local/lib/python3.6/dist-packages/modelforge/model.py", line 223, in cache_dir
    raise RuntimeError("modelforge is not configured; look at modelforge.configuration. "
RuntimeError: modelforge is not configured; look at modelforge.configuration. Depending on your objective you may or may not want to create a modelforgecfg.py file which sets VENDOR and the rest.
```

This does not happen to me with `python3 -m lookout run lookout.style.format -s`

**Comment by rporres** [comment]
@vmarkovtsev How is the analyzer accessing data in `--fs XXX` in terms of read/write operations? I'm thinking about the type of storage that should be configured.

**Comment by vmarkovtsev** [comment]
@rporres it is sequential RW

**Comment by rporres** [comment]
@mcuadros @smola This is the kind of things to consider when we discuss storage in production cluster. Most likely we will need some kind of shared storage to keep this data.

**Comment by smola** [comment]
@rporres Definitely, either HDFS or Gluster could do a good job here.

**Comment by bzz** [comment]
I could move forward with running a Docker image by setting `MODELFORGE_VENDOR` env var, @vmarkovtsev do you think it should be done in the Dockerfile ?

```
$ docker run -it -p2000:2000 --rm -e MODELFORGE_VENDOR="source{d}"\
   -v /tmp:/tmp --net lookout_default --link lookout_postgres_1 srcd/style-analyzer\
   run lookout.style.format \
   -s 0.0.0.0:2000 --db "postgresql://postgres:postgres@lookout_postgres_1:5432/postgres"\
   --fs /tmp
```

**Comment by vmarkovtsev** [comment]
I will definitely fix this, somehow did not hit this problem when I tested.

**Comment by vmarkovtsev** [comment]
@bzz Should work now, leaving open for your resolution.
