### ISSUE TITLE
Merge flake8 and docker jobs in Travis

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/style-analyzer#303]
We run flake8 style and docker build checks in different jobs. That's fine and the best way to organize CI in an ideal world. However, we take 5 Travis slots per build which is too big at this time.

So we need to merge those two jobs together until the build slot pressure decreases.

**Comment by zurk** [comment]
After discussion, we found a better way to do the same: add style-check stage. 
https://github.com/src-d/style-analyzer/pull/306

**Comment by zurk** [comment]
ping

**Comment by vmarkovtsev** [comment]
Sorry @zurk. Done.
