### ISSUE TITLE
Create a threshold argument to limit the number of files to analyze 

### ISSUE THREAD

**Issue by warenlg** [src-d/style-analyzer#312]
As discussed during the November 8th ML sync, we believe we should limit the number of files to analyze. Indeed most of the PRs modify less than 20 files. Otherwise we would not be able to satisfy the running time constraints only because of a tiny set of heavy PRs.

**Comment by m09** [comment]
To add someprecisions: we discussed using a byte threshold instead of a number of files one since this is the more limiting factor for us.

**Comment by vmarkovtsev** [comment]
Done - we limit by the overall size
