### ISSUE TITLE
Create a script to output a single quality report gathering all specific reports we built

### ISSUE THREAD

**Issue by warenlg** [src-d/style-analyzer#313]
Currently, to evaluate the performance of the style-analyzer, we use 3 different quality reports:
* The one output by the `robust-eval` command that measure through precision and recall the analyzer's ability to fix artificial style mistakes in a repository.
* The one based on the smoke dataset, focusing on specific categories of style mistakes.
* The one Egor's worked on in this PR https://github.com/src-d/style-analyzer/pull/251

At the end we should run a single script that would compiled all those reports and output a final single performance report.

**Comment by EgorBu** [comment]
It could be done if all reports will be done as analyzers. 
Example for quality report https://github.com/src-d/style-analyzer/pull/326

**Comment by vmarkovtsev** [comment]
Ad-hoc command line entries are fine too, I think.

**Comment by vmarkovtsev** [comment]
This will be a Makefile and the work happens in https://github.com/src-d/style-analyzer/pull/397 by @warenlg
