### ISSUE TITLE
Fix the UAST check that degrades the analyzer's precision

### ISSUE THREAD

**Issue by warenlg** [src-d/style-analyzer#338]
When plotting the Precision/Recall curves with and without the UAST check, we saw that the UAST check degraded the precision of the analyzer which is impossible ; this feature should only improve the precision by dropping predictions that are breaking the UAST. The blue curve can not be under the orange one.

![model_precision_bad](https://user-images.githubusercontent.com/24694845/48882634-99ffb580-ee1b-11e8-90b6-fda12e83a2c2.png)

When looking at the code and the predictions with the visualizer, it turns out the bug comes from the way we generate code from predictions involving indentation increase/decrease.

**Comment by warenlg** [comment]
I tried to use the `generate` method from `CodeGenerator` but it looks like the function meets some difficulties when tabs and spaces are mixed in the indentation. Thus I decide to fix the snippet generation directly in `postprocess.py`

**Comment by warenlg** [comment]
After running the `robust-eval` quality report with the right UAST check, the curves look better. Indeed the blue curve is overhead the orange one.

![model_precision](https://user-images.githubusercontent.com/24694845/48883495-5a879800-ee20-11e8-8eed-035d3cb0c8f0.png)

**Comment by zurk** [comment]
> function meets some difficulties when tabs and spaces are mixed in the indentation

Yes, it can happen. I create an issue for myself. Please share your example so I can test it.
https://github.com/src-d/style-analyzer/issues/341
