### ISSUE TITLE
Optimize the UAST breaking preds filtering based on recent feedback

### ISSUE THREAD

**Issue by warenlg** [src-d/style-analyzer#351]
Reminder to optimize the postprocessing method:
* Extract the loop body to a separate function https://github.com/src-d/style-analyzer/pull/346#discussion_r236192003
* Refactor `filter_uast_breaking_preds` into a class with the appropriate Babelfish initialization https://github.com/src-d/style-analyzer/pull/289#pullrequestreview-175909725

**Comment by warenlg** [comment]
This issue has been fixed by @m09 through this PR https://github.com/src-d/style-analyzer/pull/373 I reviewed and tested

**Comment by m09** [comment]
For the _refactor into a class_ part, we don't do any bblfsh init or any init of any kind so I think it's safe to close this issue.
