### ISSUE TITLE
Rules model with 0 rules are not graciously handled

### ISSUE THREAD

**Issue by EgorBu** [src-d/style-analyzer#353]
Hi,
It would be nice to handle corner case when analyzer gives trained rules with 0 rules.
Current behavior - crash (unfortunately I don't have crash report).
Expected behavior - no report or no predictions or default predictions.

Repository where it appeared several PRs ago `vue-cli`
`https://github.com/vuejs/vue-cli --to 2024f4e52097bed96b527d2e519dccba334f434b --from 85e4f9839ba88d1283b10bb3112582792b8dac6e` 
```
style.format.analyzer.FormatAnalyzer/['1'] file:///tmp/tmpyhy3k152/vue-cli 2024f4e52097bed96b527d2e519dccba334f434b

# javascript
0 rules, avg.len. 0.0
```

**Comment by m09** [comment]
Fixed in #440.
