### ISSUE TITLE
Distinguish between accumulated indentation Node and regular one

### ISSUE THREAD

**Issue by zurk** [src-d/style-analyzer#355]
There are two cases that are hard to do distinguish.
1. VirtualNode `vnode` contains accumulated indentation. `vnode.y` is always None. 
2. VirtualNode contains formatting symbols. There was some value in `vnode.y` until PR https://github.com/src-d/style-analyzer/pull/332. Now you can filter this label and get `vnode.y` equal to None. 

So, I suggest to put a flag `VirtualNode.is_accumulated_indentation` and set it in parser because the only parser knows exactly which tokens contain accumulated indentation.

It is requered to distinguish between accumulated indentation Node and the regular one for CodeGenerator. And code fails to generate file because of it: https://travis-ci.org/src-d/style-analyzer/jobs/460662957#L2802

**Comment by zurk** [comment]
cc @vmarkovtsev

**Comment by m09** [comment]
@zurk this is closely related to the ongoing refactoring, we should discuss it at tomorrow sync :) (or even today)

**Comment by zurk** [comment]
Ok, I make a comment in PR I created.
