### ISSUE TITLE
Fix label support filtering

### ISSUE THREAD

**Issue by m09** [src-d/style-analyzer#369]
Current reports show labels with low support even though they should be filtered.

**Comment by m09** [comment]
@EgorBu I think the low support rules are artificial ones. It can be check by looking at their attributes (they don't have any comparison). If this is the case then this is not a bug but intended to handle quote fixes. Let me know if you have confirmation/infirmation of this :)

**Comment by zurk** [comment]
So, actually the filtering we have before was wrong and we disable it: https://github.com/src-d/style-analyzer/issues/387

We do not filter labels properly on `analyze` stage. I think the best way to do it is to exclude filtered labels from `labels_to_class_sequences` and `class_sequences_to_labels` during train stage and filter by this mappings during analyze stage.

**Comment by zurk** [comment]
I think before implementing it I think this issue requires further discussion because if we do that we will be unable to fix any weird format sequence.

**Comment by vmarkovtsev** [comment]
Fix=pin or fix=correct? Any=all or any=some?

**Comment by zurk** [comment]
Fix=pin and correct
Any=all

So if you have PR with something like `<newline><space><newline><space><newline><space>` instead of  `<newline>` it is something that potentially can be easily fixed but we will just ignore it.

**Comment by vmarkovtsev** [comment]
@zurk @m09 so what's the plan?

**Comment by m09** [comment]
Fixed in #415
