### ISSUE TITLE
Investigate low recall and weird precisions in PR curves

### ISSUE THREAD

**Issue by m09** [src-d/style-analyzer#370]

**Comment by warenlg** [comment]
Currently investigating on science3

**Comment by warenlg** [comment]
One of the cause is https://github.com/src-d/style-analyzer/issues/374. However I raises another specific issue because there might be other reasons and bugs hidden.

**Comment by warenlg** [comment]
Other reason https://github.com/src-d/style-analyzer/issues/377

**Comment by vmarkovtsev** [comment]
@warenlg What's the status of this?

**Comment by warenlg** [comment]
Around this issue, I fixed :
* https://github.com/src-d/style-analyzer/pull/378
* https://github.com/src-d/style-analyzer/pull/376
And published the quality report here https://github.com/src-d/style-analyzer/pull/397

Now the recall came back to normal values we used to have (around 0.4) and the precision looks good also, so to me, this issue should be closed

**Comment by vmarkovtsev** [comment]
Done
