### ISSUE TITLE
Test repository is damaged.  

### ISSUE THREAD

**Issue by zurk** [src-d/style-analyzer#395]
I found out that our repository for testing (https://github.com/src-d/style-analyzer/blob/423c9d86084acedbab12cd1d603ade9e733f567e/lookout/style/format/tests/jquery.tar.xz) is not repository anymore (there is no `.git`). Long run rests runs `lookout-sdk` which requires git repo:

https://github.com/src-d/style-analyzer/blob/423c9d86084acedbab12cd1d603ade9e733f567e/lookout/style/format/tests/test_analyzer_integration.py#L131

+1 to run long tests from time to time.

**Comment by zurk** [comment]
@warenlg I think you wanted to accelerate some tests? That is why you deleted a lot of files inside? I think it is fine to do that but you should recreate git repo and check long tests.

**Comment by warenlg** [comment]
@zurk Indeed I removed the majority of the files, some of them were huge and I thought it was useless to test the logic on such files. If you PRed the previous repo archive, Travis is not going to pass because not responding

**Comment by zurk** [comment]
yeah, I was going to check and see you are right. Some parts require more than 10 mins to output something so Travis decides to kill it. 
Can I ask you to fix this issue?

**Comment by zurk** [comment]
Actually, Python 3.5 passes. So maybe there is another reason.

**Comment by zurk** [comment]
ok, I did it because I need it to make tests pass in https://github.com/src-d/style-analyzer/pull/326
I decided to leave more files in this repos, but smaller one mostly. Let's see how it goes.
