### ISSUE TITLE
Move lookout/style/__main__.py to another package

### ISSUE THREAD

**Issue by zurk** [src-d/style-analyzer#402]
To make `python3 -m lookout run ...` work without style-analyzer package.

**Comment by vmarkovtsev** [comment]
This should not work this way. Our main is the tools which are not used directly in any way.

**Comment by zurk** [comment]
So, let me explain it carefully.  We have a general cmd entry point for all analyzers in 
`lookout/__main__.py` which allow us to run `python3 -m lookout run ...`

However, when we move `lookout.core` to a separate package, we forget to move this file. 
So when you install `lookout-sdk-ml` you do not have `lookout/__main__.py` but you should. 

So let's move `lookout/__main__.py` to `lookout-sdk-ml` or even to `lookout-sdk`

**Comment by zurk** [comment]
I look carefully and find that we have `__main__.py` in `lookout-sdk-ml`, so we should just delete it in `style-analyzer`.

https://github.com/src-d/lookout-sdk-ml/blob/master/lookout/__main__.py
