### ISSUE TITLE
Current setup can install two incompatibles versions of asdf

### ISSUE THREAD

**Issue by m09** [src-d/style-analyzer#412]
Right now it's possible to have `asdf==2.2.1` installed, that understands the versions 1.0.0, 1.1.0 and 1.2.0 of the ASDF standard and `asdf==2.3` installed, which uses version 1.3.0 of that standard.

That leads to the following message when a model was trained on some env with `asdf==2.3` and read on some env with `asdf==2.2.1`:

    ValueError: This version of the asdf package (2.2.1) only understands how to handle versions 1.0.0, 1.1.0 and 1.2.0 of the ASDF Standard. Got '1.3.0'

Fix probably belongs to modelforge. cc @vmarkovtsev.

**Comment by vmarkovtsev** [comment]
I will pin it to 2.2.1

**Comment by vmarkovtsev** [comment]
Fixed in `lookout-sdk-ml==0.4.0` and `sourced-ml==0.7.2`
