### ISSUE TITLE
JSON logging

### ISSUE THREAD

**Issue by rporres** [src-d/style-analyzer#43]
JSON is the standard logging format for source{d} applications in production. It doesn't have to be the default, just to have the possibility to switch it on with an env variable or from the command line

**Comment by vmarkovtsev** [comment]
This is already implemented.

**Comment by rporres** [comment]
Which is the flag I should be passing?

**Comment by vmarkovtsev** [comment]
Should be `--log-structured` (I wrote a cool description of everything in `--help` which is git-like).

**Comment by rporres** [comment]
Testing that, thx!

**Comment by vmarkovtsev** [comment]
I am writing to stdout. Does it want stderr instead?

**Comment by vmarkovtsev** [comment]
The check is simple @rporres - run it in your terminal and you will see the jsons.

**Comment by rporres** [comment]
> I am writing to stdout. Does it want stderr instead?

stdout should be fine, but apparently it is not working when running under Docker...

**Comment by vmarkovtsev** [comment]
I just checked and the very same image works perfectly with structured logging for me.
I think the problem is in flushing stdout.

**Comment by rporres** [comment]
hmm, then why it doesn't happen with normal logging?

**Comment by vmarkovtsev** [comment]
The normal logging goes to stderr which is not buffered - this is Python standard.

**Comment by vmarkovtsev** [comment]
Fixed by https://github.com/src-d/style-analyzer/pull/44

**Comment by rporres** [comment]
thx, @vmarkovtsev

**Comment by vmarkovtsev** [comment]
The docker image is rebuilding https://hub.docker.com/r/srcd/style-analyzer/builds/

**Comment by rporres** [comment]
Works fine after the fix. Thx, @vmarkovtsev
