### ISSUE TITLE
Find a way how to analyze the quality report results

### ISSUE THREAD

**Issue by zurk** [src-d/style-analyzer#437]
on the trail of https://github.com/src-d/style-analyzer/pull/326#issuecomment-445241039

> The important one. The problem of the current approach is the following. In case you want to analyze the report with Python, it is super inconvenient because you need to parse reports back. And it is impossible to analyze a lot of reports manually. So we should generate report data first (confusion matrixes mostly) and then generate a report / analyze it. It is something that I do for smoke evaluation dataset and it is super convenient.

Also, @vmarkovtsev have an additional  opinion about this: 
https://github.com/src-d/style-analyzer/pull/326#issuecomment-446217540
> The problem with the solution you propose is data duplication and two sets of files. They can go out of sync (I want to leave notes in markdown reports in the future!), we are not going to commit machine-readable data to the repo and hence we will discard it. Besides, generating md in a single pass is much simpler, faster and easier than doing it in two passes. Just because 1 < 2.

**Comment by vmarkovtsev** [comment]
This was fixed for the quality report by including the raw JSON at the bottom and has already paid off.
