### ISSUE TITLE
Pass the long running tests

### ISSUE THREAD

**Issue by warenlg** [src-d/style-analyzer#477]
After fixing some bugs, the tests fail at the attribute pruning step returning a `ERROR analysis failed analyzer=test-analyzes app=lookout-sdk error=rpc error: code = DeadlineExceeded desc = Deadline Exceeded provider=`

**Comment by zurk** [comment]
Looks like old version of lookout-sdk. App team removed timeout in v0.6.0 and later.
Which version is it?

**Comment by warenlg** [comment]
I'm using the latest lookout-sdk v0.6.0

**Comment by warenlg** [comment]
This one for example `LONG_TESTS=1 python3 test_analyzer_integration.py` failed after spending too much time on attribute pruning

**Comment by EgorBu** [comment]
reproduced the error

**Comment by EgorBu** [comment]
```console
/tmp/lookout-sdk-ml-tests/server version
lookout-sdk v0.5.0 built on 11-23-2018_16_43_04
```
Found the problem - I have an old version of server too. Locally it caches the `server` so you need to delete it manually.
@warenlg , could you check it and close the issue?

**Comment by warenlg** [comment]
Yes @EgorBu this is a fix ! I'm back testing other files

**Comment by warenlg** [comment]
No more errors, with the recent PRs, the long tests passed
