### ISSUE TITLE
Save the achieved metrics during training to the model

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/style-analyzer#499]
We currently do not measure precision, recall, etc. in `train()`. We need to measure them and save the values to the model file.

**Comment by zurk** [comment]
Solved with https://github.com/src-d/style-analyzer/pull/534.
@vmarkovtsev please confirm and close.

**Comment by vmarkovtsev** [comment]
I confirm, `classification_report` is saved for each model.
