### ISSUE TITLE
Incorrect max line filtering of the input files

### ISSUE THREAD

**Issue by warenlg** [src-d/style-analyzer#501]
Currently, when you train a model, you always have during the files preprocessing:
`DEBUG:FormatAnalyzer:excluded 0/X files by max line length 500` because the logic for max line filtering is duplicated and the actual filtering happens earlier.

Could be the opportunity to factorize `filter_files`, `filter_filepaths`, `prepare_files`, etc

**Comment by vmarkovtsev** [comment]
@warenlg Where does the actual filtering take place then?

**Comment by warenlg** [comment]
here https://github.com/src-d/style-analyzer/blob/master/lookout/style/format/files_filtering.py#L29
and the log comes from https://github.com/src-d/lookout-sdk-ml/blob/master/lookout/core/lib.py#L101

**Comment by warenlg** [comment]
Fixed by https://github.com/src-d/style-analyzer/pull/652
