### ISSUE TITLE
Remove files_filtering.py and use lookout-sdk-ml

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/style-analyzer#502]
`style-analyzer/lookout/style/format/files_filtering.py`duplicates https://github.com/src-d/lookout-sdk-ml/blob/master/lookout/core/lib.py#L101 as @warenlg found. We need to add the missing regexp filtering feature and switch to using the SDK function.

**Comment by zurk** [comment]
Is it solved, guys? There is no such file `style-analyzer/lookout/style/format/files_filtering.py` anymore.

**Comment by vmarkovtsev** [comment]
Not really, @warenlg is pending to rebase what's left in his older commits.

**Comment by warenlg** [comment]
Yes, I'm on it right now

**Comment by warenlg** [comment]
Order of review required:
1. https://github.com/src-d/lookout-sdk-ml/pull/64
2. lookout release
3. https://github.com/src-d/style-analyzer/pull/652
