### ISSUE TITLE
Fix the last-minute problems with the reports

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/style-analyzer#511]
- [x] Fix recall and f1 being the same as precision
- [x] Check for None in the summary report and handle gracefully
- [x] Investigate and fix (if easy to fix) the crash on meteor

**Comment by vmarkovtsev** [comment]
\+ https://github.com/src-d/ml-backlog/issues/1

**Comment by vmarkovtsev** [comment]
Reports wer efixed in https://github.com/src-d/style-analyzer/pull/512
@EgorBu has regenerated the summary for the quality report.

The problem with meteor is some weird Unicode, is fixed in https://github.com/src-d/style-analyzer/pull/519

**Comment by zurk** [comment]
Ok, with fix https://github.com/src-d/style-analyzer/pull/527 meteor should work fine and I am going to check it today.

**Comment by zurk** [comment]
the meteor is still running (attributes prunning)
I am going to run another report collection without attributes prunning.

**Comment by zurk** [comment]
Fresh raw report summaries without attributes pruning for https://github.com/src-d/style-analyzer/commit/171ebabf5399d7fe2ab812903a58e854a1b1e519

# How to reproduce: 
1. Disable pruning in `analyzer.py`: `"prune_attributes": False, "uncertain_attributes": False`
2. Run `make report-quality`

# Train report

| repo               |   precision |   recall |   full_recall |    f1 |   full_f1 |   ppcr |   support |   full_support |   Rules Number |   Average Rule Len |
|:-------------------|------------:|---------:|--------------:|------:|----------:|-------:|----------:|---------------:|---------------:|-------------------:|
| 30-seconds-of-code |       0.938 |    0.938 |         0.905 | 0.938 |     0.921 |  0.964 |     65310 |          67737 |        151     |            7.05298 |
| axios              |       0.960 |    0.960 |         0.959 | 0.960 |     0.959 |  1.000 |     21126 |          21130 |        143     |            7.27273 |
| carlo              |       0.961 |    0.961 |         0.909 | 0.961 |     0.934 |  0.945 |      5227 |           5529 |         78     |            6.20513 |
| citgm              |       0.978 |    0.978 |         0.347 | 0.978 |     0.513 |  0.355 |      7797 |          21941 |         14     |            6       |
| create-react-app   |       0.947 |    0.947 |         0.888 | 0.947 |     0.916 |  0.938 |     15687 |          16718 |        101     |            6.55446 |
| express            |       0.970 |    0.970 |         0.969 | 0.970 |     0.970 |  1.000 |     78382 |          78411 |        269     |            9.60223 |
| freeCodeCamp       |       0.958 |    0.958 |         0.799 | 0.958 |     0.872 |  0.835 |     95151 |         114020 |        474     |            9.85654 |
| jquery             |       0.981 |    0.981 |         0.880 | 0.981 |     0.928 |  0.897 |    176731 |         197072 |        391     |            9.4757  |
| react              |       0.977 |    0.977 |         0.977 | 0.977 |     0.977 |  1.000 |    304322 |         304465 |        780     |           11.6692  |
| react-native       |       0.963 |    0.963 |         0.855 | 0.963 |     0.906 |  0.889 |    235463 |         264961 |        693     |           13.6825  |
| redux              |       0.975 |    0.975 |         0.893 | 0.975 |     0.932 |  0.917 |     13550 |          14783 |         25     |            6.56    |
| storybook          |       0.969 |    0.969 |         0.965 | 0.969 |     0.967 |  0.997 |    160802 |         161366 |        494     |           10.2692  |
| telescope          |       1.000 |    1.000 |         0.166 | 1.000 |     0.284 |  0.166 |       121 |            731 |          2     |            2       |
| vue-cli            |       0.941 |    0.941 |         0.844 | 0.941 |     0.890 |  0.897 |       639 |            712 |         10     |            5.1     |
| meteor             |       0.970 |    0.970 |         0.774 | 0.970 |     0.861 |  0.799 |    269665 |         337627 |        557     |           12.0646  |
| webpack            |       0.971 |    0.971 |         0.879 | 0.971 |     0.922 |  0.905 |    324030 |         358012 |        666     |           11.6306  |
| evergreen          |       0.946 |    0.946 |         0.933 | 0.946 |     0.940 |  0.986 |     37867 |          38387 |        368     |           12.0897  |
| atom               |       0.983 |    0.983 |         0.942 | 0.983 |     0.962 |  0.958 |    254474 |         265521 |        440     |           11.0773  |
| node               |       0.978 |    0.978 |         0.900 | 0.978 |     0.937 |  0.920 |    344373 |         374298 |        641     |           13.8034  |
| Average            |       0.967 |    0.967 |         0.831 | 0.967 |     0.873 |  0.861 |    126880 |         139127 |        331.421 |            9.051   |
| Weighted average   |       0.972 |    0.972 |         0.886 | 0.972 |     0.925 |  0.919 |           |                |                |                    |

# Test report

| repo               |   precision |   recall |   full_recall |    f1 |   full_f1 |   ppcr |   support |   full_support |   Rules Number |   Average Rule Len |
|:-------------------|------------:|---------:|--------------:|------:|----------:|-------:|----------:|---------------:|---------------:|-------------------:|
| 30-seconds-of-code |       0.951 |    0.951 |         0.930 | 0.951 |     0.940 |  0.977 |   10773   |        11021   |        151     |            7.05298 |
| axios              |       0.940 |    0.940 |         0.895 | 0.940 |     0.917 |  0.951 |    5333   |         5605   |        143     |            7.27273 |
| carlo              |       0.878 |    0.878 |         0.817 | 0.878 |     0.846 |  0.931 |    1825   |         1960   |         78     |            6.20513 |
| citgm              |       0.936 |    0.936 |         0.873 | 0.936 |     0.904 |  0.933 |    4400   |         4717   |         14     |            6       |
| create-react-app   |       0.895 |    0.895 |         0.772 | 0.895 |     0.829 |  0.862 |    2038   |         2364   |        101     |            6.55446 |
| express            |       0.937 |    0.937 |         0.918 | 0.937 |     0.928 |  0.979 |   14908   |        15223   |        269     |            9.60223 |
| freeCodeCamp       |       0.928 |    0.928 |         0.891 | 0.928 |     0.909 |  0.960 |   21988   |        22901   |        474     |            9.85654 |
| jquery             |       0.972 |    0.972 |         0.933 | 0.972 |     0.952 |  0.959 |   39859   |        41545   |        391     |            9.4757  |
| react              |       0.943 |    0.943 |         0.919 | 0.943 |     0.931 |  0.974 |   54059   |        55481   |        780     |           11.6692  |
| react-native       |       0.940 |    0.940 |         0.904 | 0.940 |     0.922 |  0.962 |   48067   |        49982   |        693     |           13.6825  |
| redux              |       0.937 |    0.937 |         0.791 | 0.937 |     0.858 |  0.844 |    7451   |         8827   |         25     |            6.56    |
| storybook          |       0.940 |    0.940 |         0.896 | 0.940 |     0.917 |  0.953 |   35718   |        37476   |        494     |           10.2692  |
| telescope          |       0.806 |    0.806 |         0.460 | 0.806 |     0.585 |  0.570 |     170   |          298   |          2     |            2       |
| vue-cli            |       0.892 |    0.892 |         0.646 | 0.892 |     0.749 |  0.725 |     600   |          828   |         10     |            5.1     |
| meteor             |       0.900 |    0.900 |         0.761 | 0.900 |     0.825 |  0.845 |   83280   |        98504   |        557     |           12.0646  |
| webpack            |       0.957 |    0.957 |         0.915 | 0.957 |     0.936 |  0.956 |   72580   |        75888   |        666     |           11.6306  |
| evergreen          |       0.828 |    0.828 |         0.805 | 0.828 |     0.817 |  0.972 |   17891   |        18407   |        368     |           12.0897  |
| atom               |       0.955 |    0.955 |         0.950 | 0.955 |     0.952 |  0.995 |   19807   |        19916   |        440     |           11.0773  |
| node               |       0.965 |    0.965 |         0.918 | 0.965 |     0.941 |  0.951 |   68922   |        72447   |        641     |           13.8034  |
| Average            |       0.921 |    0.921 |         0.842 | 0.921 |     0.877 |  0.911 |   26824.7 |        28599.5 |        331.421 |            9.051   |
| Weighted average   |       0.938 |    0.938 |         0.880 | 0.938 |     0.907 |  0.941 |           |                |                |                    |

# Full reports
[quality-report.tar.gz](https://github.com/src-d/style-analyzer/files/2782201/quality-report.tar.gz)

**Comment by zurk** [comment]
Fresh raw report summaries **with** attributes pruning for https://github.com/src-d/style-analyzer/commit/171ebabf5399d7fe2ab812903a58e854a1b1e519

# How to reproduce: 
2. Run `make report-quality`

# Train report

| repo               |   precision |   recall |   full_recall |    f1 |   full_f1 |   ppcr |   support |   full_support |   Rules Number |   Average Rule Len |
|:-------------------|------------:|---------:|--------------:|------:|----------:|-------:|----------:|---------------:|---------------:|-------------------:|
| 30-seconds-of-code |       0.924 |    0.924 |         0.901 | 0.924 |     0.913 |  0.975 |     65995 |          67697 |        151     |            6.56954 |
| axios              |       0.951 |    0.951 |         0.951 | 0.951 |     0.951 |  1.000 |     21329 |          21333 |        143     |            7.0979  |
| carlo              |       0.918 |    0.918 |         0.876 | 0.918 |     0.897 |  0.954 |      5960 |           6245 |         78     |            6.0641  |
| citgm              |       0.977 |    0.977 |         0.352 | 0.977 |     0.517 |  0.360 |      7894 |          21942 |         14     |            5.57143 |
| create-react-app   |       0.947 |    0.947 |         0.888 | 0.947 |     0.917 |  0.938 |     15696 |          16727 |        101     |            5.64356 |
| express            |       0.965 |    0.965 |         0.965 | 0.965 |     0.965 |  1.000 |     78608 |          78637 |        269     |            9.46468 |
| freeCodeCamp       |       0.911 |    0.911 |         0.829 | 0.911 |     0.868 |  0.911 |    104085 |         114310 |        474     |            9.1097  |
| jquery             |       0.960 |    0.960 |         0.880 | 0.960 |     0.918 |  0.918 |    180819 |         197074 |        391     |            9.1202  |
| react              |       0.935 |    0.935 |         0.935 | 0.935 |     0.935 |  1.000 |    304493 |         304548 |        780     |           11.4423  |
| react-native       |       0.921 |    0.921 |         0.834 | 0.921 |     0.875 |  0.906 |    264845 |         292374 |        802     |           14.3317  |
| redux              |       0.925 |    0.925 |         0.857 | 0.925 |     0.890 |  0.926 |     15039 |          16235 |         25     |            5.84    |
| storybook          |       0.892 |    0.892 |         0.890 | 0.892 |     0.891 |  0.998 |    167902 |         168319 |        494     |            9.75911 |
| telescope          |       1.000 |    1.000 |         0.166 | 1.000 |     0.284 |  0.166 |       121 |            731 |          2     |            2       |
| vue-cli            |       0.941 |    0.941 |         0.844 | 0.941 |     0.890 |  0.897 |       639 |            712 |         10     |            4.4     |
| meteor             |       0.940 |    0.940 |         0.785 | 0.940 |     0.856 |  0.836 |    278007 |         332635 |        473     |           10.2495  |
| webpack            |       0.929 |    0.929 |         0.860 | 0.929 |     0.893 |  0.926 |    329988 |         356487 |        666     |           10.961   |
| evergreen          |       0.745 |    0.745 |         0.740 | 0.745 |     0.742 |  0.994 |     42123 |          42358 |        368     |           11.144   |
| atom               |       0.941 |    0.941 |         0.923 | 0.941 |     0.932 |  0.981 |    261668 |         266751 |        376     |            8.75798 |
| node               |       0.954 |    0.954 |         0.887 | 0.954 |     0.919 |  0.930 |    347404 |         373613 |        641     |           13.2293  |
| Average            |       0.930 |    0.930 |         0.809 | 0.930 |     0.845 |  0.874 |    131190 |         140986 |        329.368 |            8.461   |
| Weighted average   |       0.932 |    0.932 |         0.867 | 0.932 |     0.897 |  0.936 |           |                |                |                    |

# Test report
| repo               |   precision |   recall |   full_recall |    f1 |   full_f1 |   ppcr |   support |   full_support |   Rules Number |   Average Rule Len |
|:-------------------|------------:|---------:|--------------:|------:|----------:|-------:|----------:|---------------:|---------------:|-------------------:|
| 30-seconds-of-code |       0.940 |    0.940 |         0.919 | 0.940 |     0.929 |  0.977 |   10773   |        11021   |        151     |            6.56954 |
| axios              |       0.935 |    0.935 |         0.892 | 0.935 |     0.913 |  0.953 |    5344   |         5605   |        143     |            7.0979  |
| carlo              |       0.871 |    0.871 |         0.823 | 0.871 |     0.847 |  0.945 |    1853   |         1960   |         78     |            6.0641  |
| citgm              |       0.928 |    0.928 |         0.880 | 0.928 |     0.903 |  0.948 |    4472   |         4717   |         14     |            5.57143 |
| create-react-app   |       0.760 |    0.760 |         0.740 | 0.760 |     0.750 |  0.974 |    2302   |         2364   |        101     |            5.64356 |
| express            |       0.935 |    0.935 |         0.918 | 0.935 |     0.927 |  0.982 |   14944   |        15223   |        269     |            9.46468 |
| freeCodeCamp       |       0.891 |    0.891 |         0.886 | 0.891 |     0.889 |  0.994 |   22771   |        22901   |        474     |            9.1097  |
| jquery             |       0.953 |    0.953 |         0.928 | 0.953 |     0.940 |  0.973 |   40438   |        41545   |        391     |            9.1202  |
| react              |       0.905 |    0.905 |         0.887 | 0.905 |     0.896 |  0.981 |   54403   |        55481   |        780     |           11.4423  |
| react-native       |       0.900 |    0.900 |         0.871 | 0.900 |     0.885 |  0.968 |   53941   |        55713   |        802     |           14.3317  |
| redux              |       0.913 |    0.913 |         0.787 | 0.913 |     0.845 |  0.863 |    7614   |         8827   |         25     |            5.84    |
| storybook          |       0.865 |    0.865 |         0.848 | 0.865 |     0.856 |  0.980 |   36745   |        37476   |        494     |            9.75911 |
| telescope          |       0.806 |    0.806 |         0.460 | 0.806 |     0.585 |  0.570 |     170   |          298   |          2     |            2       |
| vue-cli            |       0.892 |    0.892 |         0.646 | 0.892 |     0.749 |  0.725 |     600   |          828   |         10     |            4.4     |
| meteor             |       0.759 |    0.759 |         0.705 | 0.759 |     0.731 |  0.928 |   38007   |        40961   |        473     |           10.2495  |
| webpack            |       0.908 |    0.908 |         0.883 | 0.908 |     0.895 |  0.972 |   73761   |        75888   |        666     |           10.961   |
| evergreen          |       0.655 |    0.655 |         0.651 | 0.655 |     0.653 |  0.995 |   18306   |        18407   |        368     |           11.144   |
| atom               |       0.887 |    0.887 |         0.882 | 0.887 |     0.884 |  0.994 |   56237   |        56601   |        376     |            8.75798 |
| node               |       0.941 |    0.941 |         0.900 | 0.941 |     0.920 |  0.956 |   69294   |        72447   |        641     |           13.2293  |
| Average            |       0.876 |    0.876 |         0.816 | 0.876 |     0.842 |  0.930 |   26946.1 |        27803.3 |        329.368 |            8.461   |
| Weighted average   |       0.890 |    0.890 |         0.862 | 0.890 |     0.876 |  0.970 |           |                |                |                    |

**Comment by zurk** [comment]
New reports with pruning for https://github.com/src-d/style-analyzer/commit/fdf2a03976627967fa9422f1c06611f77c433380


# Train report

| repo               |   precision |   recall |   full_recall |    f1 |   full_f1 |   ppcr |   support |   full_support |   Rules Number |   Average Rule Len |
|:-------------------|------------:|---------:|--------------:|------:|----------:|-------:|----------:|---------------:|---------------:|-------------------:|
| 30-seconds-of-code |       0.942 |    0.942 |         0.899 | 0.942 |     0.920 |  0.955 |     64717 |          67751 |            155 |                6.8 |
| axios              |       0.968 |    0.968 |         0.968 | 0.968 |     0.968 |  1.000 |     20935 |          20940 |            172 |                8.2 |
| carlo              |       0.911 |    0.911 |         0.873 | 0.911 |     0.891 |  0.958 |      6032 |           6298 |            101 |                6.5 |
| citgm              |       0.982 |    0.982 |         0.888 | 0.982 |     0.933 |  0.904 |     19824 |          21928 |             18 |                7.1 |
| create-react-app   |       0.891 |    0.891 |         0.853 | 0.891 |     0.872 |  0.958 |     16796 |          17534 |             22 |                6.9 |
| express            |       0.975 |    0.975 |         0.970 | 0.975 |     0.972 |  0.995 |     69597 |          69940 |             33 |                9.5 |
| freeCodeCamp       |       0.931 |    0.931 |         0.762 | 0.931 |     0.838 |  0.818 |     90915 |         111204 |             74 |               10.4 |
| jquery             |       0.961 |    0.961 |         0.878 | 0.961 |     0.917 |  0.913 |    179920 |         197071 |            418 |                9.2 |
| react              |       0.932 |    0.932 |         0.932 | 0.932 |     0.932 |  1.000 |    312657 |         312707 |            868 |               12.0 |
| react-native       |       0.827 |    0.827 |         0.672 | 0.827 |     0.742 |  0.813 |    212891 |         261961 |            112 |               12.1 |
| redux              |       0.966 |    0.966 |         0.914 | 0.966 |     0.939 |  0.946 |     20305 |          21469 |             31 |                7.5 |
| storybook          |       0.866 |    0.866 |         0.864 | 0.866 |     0.865 |  0.998 |    168656 |         169073 |            556 |               10.3 |
| telescope          |       1.000 |    1.000 |         0.166 | 1.000 |     0.284 |  0.166 |       121 |            731 |              2 |                2.0 |
| reveal.js          |       0.914 |    0.914 |         0.911 | 0.914 |     0.912 |  0.997 |     10323 |          10350 |             32 |                8.6 |
| meteor             |       0.961 |    0.961 |         0.786 | 0.961 |     0.865 |  0.818 |    277253 |         338972 |            667 |               12.0 |
| webpack            |       0.933 |    0.933 |         0.860 | 0.933 |     0.895 |  0.921 |    332946 |         361500 |            753 |               11.1 |
| evergreen          |       0.940 |    0.940 |         0.936 | 0.940 |     0.938 |  0.996 |     37283 |          37429 |             66 |               11.2 |
| atom               |       0.984 |    0.984 |         0.979 | 0.984 |     0.982 |  0.995 |    259345 |         260552 |             53 |               12.6 |
| node               |       0.953 |    0.953 |         0.892 | 0.953 |     0.921 |  0.936 |    350344 |         374139 |            699 |               13.2 |
| average            |       0.939 |    0.939 |         0.842 | 0.939 |     0.873 |  0.899 |    128992 |         140081 |            254 |                9.3 |
| weighted average   |       0.935 |    0.935 |         0.861 | 0.935 |     0.894 |  0.926 |           |                |                |                    |

# Test report

| repo               |   precision |   recall |   full_recall |    f1 |   full_f1 |   ppcr |   support |   full_support |   Rules Number |   Average Rule Len |
|:-------------------|------------:|---------:|--------------:|------:|----------:|-------:|----------:|---------------:|---------------:|-------------------:|
| 30-seconds-of-code |       0.945 |    0.945 |         0.923 | 0.945 |     0.934 |  0.977 |     10768 |          11021 |            155 |                6.8 |
| axios              |       0.946 |    0.946 |         0.923 | 0.946 |     0.934 |  0.976 |      5472 |           5605 |            172 |                8.2 |
| carlo              |       0.868 |    0.868 |         0.829 | 0.868 |     0.848 |  0.955 |      1871 |           1960 |            101 |                6.5 |
| citgm              |       0.960 |    0.960 |         0.898 | 0.960 |     0.928 |  0.936 |      4414 |           4717 |             18 |                7.1 |
| create-react-app   |       0.881 |    0.881 |         0.839 | 0.881 |     0.860 |  0.952 |      2251 |           2364 |             22 |                6.9 |
| express            |       0.950 |    0.950 |         0.894 | 0.950 |     0.921 |  0.941 |     14324 |          15223 |             33 |                9.5 |
| freeCodeCamp       |       0.907 |    0.907 |         0.854 | 0.907 |     0.880 |  0.942 |     21577 |          22901 |             74 |               10.4 |
| jquery             |       0.954 |    0.954 |         0.930 | 0.954 |     0.942 |  0.975 |     40515 |          41545 |            418 |                9.2 |
| react              |       0.903 |    0.903 |         0.890 | 0.903 |     0.897 |  0.986 |     54679 |          55481 |            868 |               12.0 |
| react-native       |       0.793 |    0.793 |         0.748 | 0.793 |     0.770 |  0.943 |     47114 |          49982 |            112 |               12.1 |
| redux              |       0.898 |    0.898 |         0.833 | 0.898 |     0.864 |  0.927 |      8187 |           8827 |             31 |                7.5 |
| storybook          |       0.843 |    0.843 |         0.829 | 0.843 |     0.836 |  0.984 |     36864 |          37476 |            556 |               10.3 |
| telescope          |       0.806 |    0.806 |         0.460 | 0.806 |     0.585 |  0.570 |       170 |            298 |              2 |                2.0 |
| reveal.js          |       0.897 |    0.897 |         0.755 | 0.897 |     0.820 |  0.842 |      8395 |           9974 |             32 |                8.6 |
| meteor             |       0.860 |    0.860 |         0.774 | 0.860 |     0.815 |  0.900 |     88677 |          98504 |            667 |               12.0 |
| webpack            |       0.917 |    0.917 |         0.900 | 0.917 |     0.909 |  0.982 |     74527 |          75888 |            753 |               11.1 |
| evergreen          |       0.894 |    0.894 |         0.857 | 0.894 |     0.875 |  0.958 |     17642 |          18407 |             66 |               11.2 |
| atom               |       0.931 |    0.931 |         0.906 | 0.931 |     0.918 |  0.973 |     19386 |          19916 |             53 |               12.6 |
| node               |       0.937 |    0.937 |         0.926 | 0.937 |     0.931 |  0.989 |     71622 |          72447 |            699 |               13.2 |
| average            |       0.899 |    0.899 |         0.840 | 0.899 |     0.867 |  0.932 |     27813 |          29080 |            254 |                9.3 |
| weighted average   |       0.896 |    0.896 |         0.857 | 0.896 |     0.875 |  0.958 |           |                |                |                    |

**Comment by vmarkovtsev** [comment]
@zurk I feel that Babelfish is playing tricks again. For example:

```
react-native | 0.793
```

**Comment by zurk** [comment]
yes!

**Comment by vmarkovtsev** [comment]
@zurk Can you please attach the logs

**Comment by zurk** [comment]
yes, I updated https://github.com/src-d/style-analyzer/issues/511#issuecomment-458083984.

**Comment by vmarkovtsev** [comment]
react-native on my laptop:

train

| repo             |   precision |   recall |   full_recall |    f1 |   full_f1 |   ppcr |   support |   full_support |   Rules Number |   Average Rule Len |
|:-----------------|------------:|---------:|--------------:|------:|----------:|-------:|----------:|---------------:|---------------:|-------------------:|
| react-native     |       0.827 |    0.827 |         0.672 | 0.827 |     0.742 |  0.813 |    212891 |         261961 |            112 |               12.1 |
| average          |       0.827 |    0.827 |         0.672 | 0.827 |     0.742 |  0.813 |    212891 |         261961 |            112 |               12.1 |
| weighted average |       0.827 |    0.827 |         0.672 | 0.827 |     0.742 |  0.813 |           |                |                |                    |

test

| repo             |   precision |   recall |   full_recall |    f1 |   full_f1 |   ppcr |   support |   full_support |   Rules Number |   Average Rule Len |
|:-----------------|------------:|---------:|--------------:|------:|----------:|-------:|----------:|---------------:|---------------:|-------------------:|
| react-native     |       0.793 |    0.793 |         0.748 | 0.793 |     0.770 |  0.943 |     47114 |          49982 |            112 |               12.1 |
| average          |       0.793 |    0.793 |         0.748 | 0.793 |     0.770 |  0.943 |     47114 |          49982 |            112 |               12.1 |
| weighted average |       0.793 |    0.793 |         0.748 | 0.793 |     0.770 |  0.943 |           |                |                |                    |

**Comment by vmarkovtsev** [comment]
@zurk Can you try without the 2MB limit on react-native.

**Comment by vmarkovtsev** [comment]
The original issue has been resolved. Let's open another one.
