### ISSUE TITLE
Remove global indentation algorithm from CodeGenerator

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/style-analyzer#522]
Local indentation is clearly better so we drop the global one and simplify the code.

**Comment by zurk** [comment]
The first part in PR: https://github.com/src-d/style-analyzer/pull/584

To continue with this issue I should implement https://github.com/src-d/style-analyzer/issues/523 first

**Comment by zurk** [comment]
After a lot of bug fixing work here we report result for https://github.com/src-d/style-analyzer/commit/eb2ec03d702cfbacfe2bfd1601cede2320ea4884
[quality-report-eb2ec03d702cfbacfe2bfd1601cede2320ea4884.tar.gz](https://github.com/src-d/style-analyzer/files/2864951/quality-report-eb2ec03d702cfbacfe2bfd1601cede2320ea4884.tar.gz)
