### ISSUE TITLE
[bug] comments can't be batched together

### ISSUE THREAD

**Issue by EgorBu** [src-d/style-analyzer#539]
https://github.com/EgorBu/carlo/pull/6#discussion_r248745156
One of the key points of lookout - apply changes in 1 click - somehow it's not possible.

**Comment by vmarkovtsev** [comment]
@zurk There are some quality problems and some presentation problems.

The quality problems are not so important at this point; the only presentation bug is with comments:

- https://github.com/EgorBu/carlo/pull/6#discussion_r248745156
- https://github.com/EgorBu/carlo/pull/6#discussion_r248745156

**Comment by zurk** [comment]
@vmarkovtsev looks like you create a list with two identical links.

**Comment by EgorBu** [comment]
![possible_bug](https://user-images.githubusercontent.com/2606702/51383211-190e2300-1b19-11e9-9b2b-8be0942b2f57.png)
it should help better understand - the button `Add suggestion to batch` is disabled because of some reason

**Comment by zurk** [comment]
ah, you about that! Now I see. Ok, I'll create another issue about my [observations](https://github.com/src-d/style-analyzer/issues/539#issuecomment-455482091)

**Comment by EgorBu** [comment]
Anyway, we need to investigate the limitations of GitHub `suggestion feature` - to be able to provide applicable `suggestions` in the future.

**Comment by EgorBu** [comment]
So, it's possible from the tab for files/changes but not possible from the discussion tab.
https://github.com/EgorBu/carlo/pull/6/files#r248745156
https://github.com/EgorBu/carlo/pull/6#discussion_r248745156
