### ISSUE TITLE
Migrate from v1 JS driver to v2

### ISSUE THREAD

**Issue by zurk** [src-d/style-analyzer#578]
v1 is not maintained for a long time and there is a bunch of problem with v1 JS driver that expected to be fixed only in v2 version. 
For example https://github.com/bblfsh/javascript-driver/issues/54

We should consider migrating after we finish with a refactoring milestone.

**Comment by bzz** [comment]
Issue has been moved to https://github.com/bblfsh/javascript-driver/issues/54

**Comment by zurk** [comment]
yup, it old link redirects to a new one but I changed it anyway, thanks!

**Comment by zurk** [comment]
duplicate of https://github.com/src-d/style-analyzer/issues/666
