### ISSUE TITLE
Split quotes tokens from "regular" formatting tokens such as spaces, newlines etc.

### ISSUE THREAD

**Issue by zurk** [src-d/style-analyzer#579]
Quotes are different from the main set of tokens we consider. 

Now we get such labels as `"⏎⏎⇥⁺⇥⁺`. It makes much harder to properly implement suggestion change feature. If you change `"⏎⏎⇥⁺⇥⁺` to `'⏎⏎⇥⁺⇥⁺` it is a first line change, and to `"⏎⏎⏎⇥⁺⇥⁺` it is second line change. 

This change should not make our ML problem ill-posed.

I think when we include `;` token for JS (https://github.com/src-d/style-analyzer/issues/498), we also should not merge it for the same reason. 

It is also the first step to separate quotes handling to different model one day (https://github.com/src-d/style-analyzer/issues/525)

@m09 please tell if you see any drawbacks for this proposal.

**Comment by m09** [comment]
It is a good change :+1: I thought about it a bit and it should not cause new problems.
