### ISSUE TITLE
Improve optional arguments type annotations

### ISSUE THREAD

**Issue by m09** [src-d/style-analyzer#634]
Following [this comment](https://github.com/src-d/style-analyzer/pull/616#pullrequestreview-206273006), we need to improve the type annotations of optional arguments (most of them lack the `Optional`).

**Comment by zurk** [comment]
I think this one is solved in https://github.com/src-d/style-analyzer/pull/644
@irinakhismatullina can you confirm?

**Comment by irinakhismatullina** [comment]
Yes it is
