### ISSUE TITLE
Generate corrected identifier

### ISSUE THREAD

**Issue by EgorBu** [src-d/style-analyzer#662]
After typos correction, a new identifier should be generated with the same style as the one before correction.

**Comment by vmarkovtsev** [comment]
@EgorBu Can you please add the core function to sourced-ml and use it here:

```python
def format_identifier(fixed: List[str], original: str) -> str:
    # TODO
```

**Comment by EgorBu** [comment]
Yes, it was the initial idea to add it to `src-d/ml`.

**Comment by EgorBu** [comment]
Solved by https://github.com/src-d/style-analyzer/pull/673
