### ISSUE TITLE
Port to the latest Javascript driver version

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/style-analyzer#666]
We need to investigate why the newer releases do not work with our code, report possible bugs to Babelfish and switch to the latest JS driver version.

**Comment by vmarkovtsev** [comment]
BTW @zurk this can be fused with the annotations refactoring.

**Comment by zurk** [comment]
I'd like to do it separately.

**Comment by vmarkovtsev** [comment]
"The latest JS driver" does not mean UASTv2 - it means upgrading the driver. And regarding the annotations, I am afraid that you will have to repeat some of the work twice otherwise.

**Comment by vmarkovtsev** [comment]
If we see that the latest JS driver works incorrectly with UASTv1 protocol, we should report it as an issue and ask LA to fix it ASAP.

**Comment by zurk** [comment]
> If we see that the latest JS driver works incorrectly with UASTv1 protocol, we should report it as an issue and ask LA to fix it ASAP.

Ok, I know that there are some issues for sure. AFAIK, UASTv1 is not clearly the same as an annotated mode in new drivers. Will see.

> And regarding the annotations, I am afraid that you will have to repeat some of the work twice otherwise.

It is fine. Annotation is about the shape of the code and this issue can touch its logic.

**Comment by zurk** [comment]
I report several minor issues related to javascript driver:
* https://github.com/bblfsh/javascript-driver/issues/65
* https://github.com/bblfsh/javascript-driver/issues/66

However, the biggest problem is on our side. We currently use `v1.2.0` driver and the driver wrongly returns Node positions for Unicode string. `v2.6.0` returns offsets for byte string, so we should recalculate them back to Unicode.

**Comment by zurk** [comment]
One more. https://github.com/bblfsh/javascript-driver/issues/67
I think that there are more files that are parsable with `v1.2.0` but not with `v2.6.0`
I am going to create a list tomorrow.

**Comment by zurk** [comment]
PR: https://github.com/src-d/style-analyzer/pull/692
Issue is blocked until v.2.7.0 driver release.
