### ISSUE TITLE
Password can be leaked in logs

### ISSUE THREAD

**Issue by rporres** [src-d/style-analyzer#670]
The first line of the log prints the `db` parameter as it is passed. That means password may be written in the logs, which should not happen, e.g (formatted)

```json
{
  "level": "info",
  "msg": "Created SQLAlchemyModelRepository(db=postgres://lookout:<PASSWORD HERE>@localhost:5432/lookout-style-analyzer?sslmode=disable, fs=/tmp/models)",
  "source": "cmdline.py:77",
  "thread": "8fbd",
  "time": "2019-03-05T18:11:31.430174000+00:00"
}
```

**Comment by vmarkovtsev** [comment]
Good catch...

**Comment by m09** [comment]
@rporres please let us know if you spot passwords in logs again. If it looks ok in new deployments we'll close :)

**Comment by m09** [comment]
Closing for now, please @rporres open a new issue if you spot passwords again.
