### ISSUE TITLE
Include the logs into the release reports

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/style-analyzer#675]
Logs are much valuable for analysis, so we should commit them together with the Markdown files. It is worth to `xz` them.

**Comment by zurk** [comment]
actually, we do: 
https://github.com/src-d/style-analyzer/blob/df9d1b2cd5926933db18f58295ddfc2503a29b49/Makefile#L67
we just should not delete it. :sweat_smile: 
I'll add compression.

**Comment by vmarkovtsev** [comment]
@zurk any progress on this?

**Comment by zurk** [comment]
there is a PR above linked to this issue: https://github.com/src-d/style-analyzer/pull/694
