### ISSUE TITLE
Create class for typos correction suggestions.

### ISSUE THREAD

**Issue by irinakhismatullina** [src-d/style-analyzer#687]
To improve readability, needed to be done a long time ago.

**Comment by EgorBu** [comment]
what's wrong with `lookout.core.api.service_analyzer_pb2.Comment`?
Or is this issue for results from `TyposCorrectorManager`?

**Comment by irinakhismatullina** [comment]
Yes, it is for the result from `TyposCorrector.suggest()`.

**Comment by irinakhismatullina** [comment]
Added in #707.
