### ISSUE TITLE
Upload the trained global typo correction model to Modelforge

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/style-analyzer#711]
Upon finishing training the global typos model, we need to upload it to Modelforge.
There should be another command added to the toolbox for it.
It requires the secret file with GCS credentials, I will provide it in DM.

Reference: https://github.com/src-d/modelforge/blob/master/doc/cmdline.md#adding-a-model

The rest of the code must be changed to use the global readonly instance of the model which is loaded at import time.

**Comment by vmarkovtsev** [comment]
Blocks #710

**Comment by vmarkovtsev** [comment]
\+ we need to provide a good description for this model which clearly specifies the intended use cases.

**Comment by irinakhismatullina** [comment]
Here is the loaded model https://github.com/src-d/models/pull/14.

**Comment by irinakhismatullina** [comment]
@vmarkovtsev I think it should be closed?
