### ISSUE TITLE
[style-analyzer] Fixing prediction

### ISSUE THREAD

**Issue by m09** [src-d/style-analyzer#93]
At this point, for the sequence `some line of code \n` which contains an extra space before newline, our (correct given the current system) prediction would be: replace ` ` by `\n` which would lead the user to believe that the system suggests having two newlines in a row. Therefore we should probably do one or several extra passes in the model with the modifications incorporated to see if the model suggests a deletion or a replacement or an insertion.

**Comment by vmarkovtsev** [comment]
@m09 this is a feature, not a bug. Trailing whitespace is a universally bad practice, disregarding any formatting style.

**Comment by vmarkovtsev** [comment]
Closing this if there are no counterarguments.

**Comment by vmarkovtsev** [comment]
Ah but if it suggests the second new line then it's bad. Yet still not sure if we need extra passes here rather than changing our feature encoding.

**Comment by m09** [comment]
It does suggest two new lines at this point. We cannot distinguish between deletion and replacement with the current system hence this issue. It even makes me think that the noop nodes are not required since they don't allow for a general solution.

**Comment by vmarkovtsev** [comment]
I see the problem, let's discuss tomorrow.

**Comment by vmarkovtsev** [comment]
Tagging @egorbu

**Comment by vmarkovtsev** [comment]
As discussed yesterday, there are two directions:

1. Importance model - on @m09 
2. Negative sampling - on @EgorBu

**Comment by EgorBu** [comment]
Before making negative sampling I decided to understand what should be sampled. I did error analysis & visualization tools (https://github.com/src-d/style-analyzer/pull/114).
Error report without auto-generated files:
```
             precision    recall  f1-score   support

2:<newline>       0.97      0.97      0.97     19850
 3:<+space>       0.95      0.97      0.96      7709
 4:<-space>       0.83      0.84      0.84      7709
        7:'       0.95      0.95      0.95      7317
        8:"       1.00      0.99      0.99     13564
   9:<noop>       1.00      1.00      1.00    231285

avg / total       0.99      0.99      0.99    287434
```
So the importance order (most -> least): `<-space>`, `'`, `<+space>`, `<newline>`

**Comment by m09** [comment]
To be able to properly measure anything I wanted to get rid of a few bugs before implementing that. I felt that if I didn't I would just be measuring random interaction between the bugs and my prediction correction (since I'm correcting what is currently failing and what currently fails mainly fails due to bugs):

1. we had many empty nodes created. I still need to fix [one place](https://github.com/src-d/style-analyzer/blob/master/lookout/style/format/features.py#L85) that pops them, I'll have a go at it this afternoon.
2. we don't create `<space>` nodes (and probably no `<tab>` nodes either).
3. before comparing what's been output to the truth, we should perform a new pass of `<noop>` insertions. ATM we don't so if the model outputs something from a `<noop>`, it's always detrimental to its accuracy: the label will always be `<noop>`. This mainly seems to happen when returning from a new line and predicting `<-space>` but there should be other places as well (at least after we fix `<noop>` prediction).
4. we could be asking for the generation of multiple tokens (especially `<-space>` or `<+space>` and their tab equivalent) from a single `<noop>`. I'm currently unsure of the best way to fix that. One way is iterative process: predict once, add `<noop>` between all predictions that were made from `<noop>` so that there are `<noop>`-s available again and predict once more. This is tricky though since we can enter some degenerate prediction loop where we output wrong stuff once and then go from there into oblivion.

I'll push fixes for 1 & 3 asap but 2 I lost some frustrating hours to already without conclusions and 4 is a big flaw of the model I'm not sure how to fix, your input is appreciated (tagging @vmarkovtsev @EgorBu).

For the actual prediction correction, I'm more and more thinking that is not the right way to do it and that with correct roles and correct prediction from and to `<noop>` another pass isn't required, apart from problem 4. as previously mentioned.

**Comment by vmarkovtsev** [comment]
1. Dense/sparse one-hot encoded features using domain knowledge - Hugo.
2. Internal types -> unified roles - Egor.
3. Bucket reserved tokens using domain knowledge - Konst.
4. +space/tab x2 x4 x8 -space/tab - Waren.

5. Split internal types by case -> one-hot.
6. Class weights.
7. Embedding on co-occurrence + clustering.
8. Metadata visualization for features (Egor's).

**Comment by zurk** [comment]
@m09 it can be helpful to use my code for Roles preprocessing for experiments: https://github.com/src-d/style-analyzer/pull/116

**Comment by vmarkovtsev** [comment]
Add OHE of the quotes.

**Comment by m09** [comment]
I consider this to be fixed since sequence were merged, please reopen if needed.
