### ISSUE TITLE
[style-analyzer] Synchronize lookout test binary and server submodule

### ISSUE THREAD

**Issue by m09** [src-d/style-analyzer#95]
As per @vmarkovtsev's suggestion in #91, we should use the hash of the submodule to retrieve a synchronized tarball.

**Comment by vmarkovtsev** [comment]
@bzz Please ensure that there is a way to associate the low-level Python SDK with the lookout binary.

**Comment by bzz** [comment]
We can have `lookout-sdk version` print the low-level SDK version number it was build across, which would be a version number of the [python library](https://pypi.org/project/lookout-sdk/)

```
$ lookout-sdk version
binary: v0.1.4 built on 09-04-2018_06_15_11

```

**Comment by vmarkovtsev** [comment]
I am on it today.
